service: mta-departure-times

provider:
  name: aws
  runtime: python3.9
  apiGateway:
    apiKeys:
      - ryan-personal

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**

functions:
  get_departures:
    handler: handler.get_departures
    environment:
      MTA_API_KEY: ${file(./secrets.json):MTA_API_KEY}
    events:
      - http:
          path: /{stop_id}
          method: get
          request:
            parameters:
              paths:
                stop_id: true
          private: true

custom:
  pythonRequirements:
    dockerizePip: false
